SELECT T.*, F.TITLE FROM (SELECT P.*, COUNT(F.ID_FILM) AS COUNT_PEOPLE FROM PEOPLE P, FILMS_PEOPLE FP, FILMS F
            WHERE P.ID_PERSON = FP.ID_PERSON
            AND F.ID_FILM = FP.ID_FILM
            AND P.ID_PERSON =1
            GROUP BY P.NAME) T, FILMS_PEOPLE FP , FILMS F
WHERE T.ID_PERSON = FP.ID_PERSON
AND F.ID_FILM = FP.ID_FILM;